# Generated by Django 4.2 on 2023-05-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='phone',
            field=models.CharField(),
        ),
    ]
